### PR TITLE
More accurate progress bar

### PR DESCRIPTION
**Pull request by praiskup**

### CODE REVIEW

**Comment by praiskup** [comment]
As a side effect, `sma_*` variables may be tweaked by class user.

**Comment by praiskup** [comment]
Ping?  Seems like silence is here for about 2 years in this repo, I'm now considering
fork and release separately.  Any objections?

**Comment by praiskup** [comment]
Please have a look.

**Comment by praiskup** [comment]
ptal :)

**Comment by verigak** [comment]
I think that if you are going to diverge from the standard moving average which is an established algorithm, you will need to make your case much better than this. Does your solution really improve on all cases, or just in the one you mention? At least you will need a few test cases that demonstrate the problem and your solution.

As an aside, doesn't _dt always contain at maximum just one item that way?

**Comment by praiskup** [comment]
The algorithm was not changed by this PR.  The problem is that
the "old" implementation works with incredibly small float numbers, doing
their sum and dividing ... which makes it very inaccurate.
[image](http://praiskup.fedorapeople.org/progress-fix.gif)

The code that uses it:
https://git.fedorahosted.org/cgit/copr.git/tree/cli/copr_cli/main.py?id=15116133574defe50#n165

**Comment by praiskup** [comment]
So PTAL.

**Comment by praiskup** [comment]
Unlucky, I can't reopen, I'll submit new PR.

**Pull request closed without merging**
