### PR TITLE
Reduce I/O Cost - no change to ETA algorithm

### PR DESCRIPTION
**Pull request by aduriseti**

### CODE REVIEW

**Comment by aduriseti** [comment]
Let me know if you want me to clean up the comment history.

**Comment by praiskup** [comment]
@aduriseti fyi, I originally thought that this will fix the code for me, but I've tested it now and the symptoms mentioned in #23 and #24 (e.g. completely broken actual speed of download) are still there.  So you are right, this is different issue (but I would be interested to hear from you whether you face **your** issues also if you try the fork.

**Comment by verigak** [comment]
@aduriseti Any update on this? I'm OK to go back to simple average, as this moving average implementation seems to be causing too much grief. I'll probably then make it easier to plug your own implementation, so hopefully everyone will be happy.

If you want to cleanup this PR to one commit that does that I'll be happy to merge it. Otherwise I'll just revert to the original implementation.

**Comment by aduriseti** [comment]
OK - I'll clean up the commit history.  Like we discussed, I split the ETA change and I/O change into separate PR.  This current PR is the I/O change.  I spent some time developing a ETA estimator that combines the stability of the simple average with the sensitivity of the moving average.  I'll push those changes in a separate PR (Idk how to do 2 PRs at once)

**Comment by aduriseti** [comment]
Flattened the commit history down to 1 for the whole PR.  Sorry for the long delay - had to expand my knowledge of git to perform this.

**Comment by aduriseti** [comment]
Hey - any updates on this PR?

**Comment by verigak** [comment]
Thanks!

**Comment by aduriseti** [comment]
Alright!

**Pull request merged**
