### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by clime**
Updated description for `avg` and `eta` properties.

### CODE REVIEW

**Comment by praiskup** [comment]
Is it rather possible to get back the old API, by some arithmetic?

Changing semantics of api is unfortunate -- that requires all consumers will have to change the code.

**Comment by verigak** [comment]
@praiskup Yes, the whole moving average thing has caused more problems than it solved. At this point the safest option is to go back to the old semantics, as this is the one that is in PyPI and most people are using.

**Comment by praiskup** [comment]
@verigak thanks, makes sense.  OTOH, I still would be interested in getting the patches from #24 into your code, it fixes the moving average calculation (and makes it a lot faster).  Moving to simple average sounds like a step back (from "user's convenience" POV).

**Comment by verigak** [comment]
Yes you are right, but I think I would prefer to keep the algorithm simple and instead provide a way to easily to plug your own algorithm. What do you think about this approach?

**Comment by praiskup** [comment]
I like the idea of "having the altorithm configurable", so if that was possible?

 But I wouldn't force users to implement the algorithm themselves, I still think the proposed moving average calculation is safe :).

**Comment by verigak** [comment]
Thanks, I ended up keeping the initial semantics

**Pull request closed without merging**
