### PR TITLE
changes to handle self.file is none case

### PR DESCRIPTION
**Pull request by shivareddyiirs**
here when self.file is none , none type object would not have isatty(). Hence modified code so that program don't check isatty when it is none.

### CODE REVIEW

**Comment by verigak** [comment]
How is:
```python
    if self.file:
        if self.file.isatty():
```
different than `if self.file and self.file.isatty():` ?

**Comment by shivareddyiirs** [comment]
update to handle isatty not in self.file

**Comment by verigak** [comment]
Can you explain what you are trying to do? The case where `self.file` is None should already be covered by commit a83f91f4b82c5ad65a0de9d3fb24fef8afaa1dea. What is this pull request trying to solve?

**Comment by shivareddyiirs** [comment]
@verigak it checks if 'isatty' is defined in the object.

**Comment by verigak** [comment]
This is handled better now, as mentioned in #50.

**Pull request closed without merging**
